[project]
name = "sps-genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "jupyter>=1.1.1",
    "numpy>=2.3.3",
    "pydantic>=2.11.9",
    "spacy>=3.8.7",
]
